DECLARE
results    NUMBER;
  v_module   VARCHAR2(100) := 'collateral';
  v_property VARCHAR2(100) := 'COL-58089_Corporate_Actions_Enhancement';
BEGIN

SELECT count(1)
INTO results
FROM lrsschemaproperties l
WHERE l.modulename = v_module
  AND l.propertyname = v_property;

IF results > 0
  THEN
    RETURN;
END IF;


EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_SECURITY DROP COLUMN CORPORATEACTION';
EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_SECURITY DROP COLUMN CORPORATEACTIONDATE';
EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_SECURITY ADD CORPORATEACTION CLOB';
EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_SECURITY ADD CORPORATEACTIONSEXCEL CLOB';
EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_SECURITY ADD CORPORATEACTIONSDATEEXCEL CLOB';

INSERT INTO lrsschemaproperties (modulename, propertyname) VALUES (v_module, v_property);
COMMIT;
END;
/
