DECLARE
results    NUMBER;
    v_module   VARCHAR2(100) := 'collateral';
    v_property VARCHAR2(100) := 'COL-52014_UPDATE_IDG_TYPE_IN_OPTIMISER_TABLES';

BEGIN

SELECT count(1) INTO results FROM lrsschemaproperties l
WHERE l.modulename = v_module
  AND l.propertyname = v_property;

IF results > 0
    THEN
        RETURN;
END IF;

EXECUTE IMMEDIATE 'ALTER TABLE OPTAGREEMENTPOOL ADD INVENTORYDELIVERYGROUP_NEW VARCHAR2(1024)';
EXECUTE IMMEDIATE 'UPDATE OPTAGREEMENTPOOL SET INVENTORYDELIVERYGROUP_NEW = INVENTORYDELIVERYGROUP';
EXECUTE IMMEDIATE 'ALTER TABLE OPTAGREEMENTPOOL DROP COLUMN INVENTORYDELIVERYGROUP';
EXECUTE IMMEDIATE 'ALTER TABLE OPTAGREEMENTPOOL RENAME COLUMN INVENTORYDELIVERYGROUP_NEW TO INVENTORYDELIVERYGROUP';

EXECUTE IMMEDIATE 'ALTER TABLE OPTASSETPOOL ADD INVENTORYDELIVERYGROUP_NEW VARCHAR2(1024)';
EXECUTE IMMEDIATE 'UPDATE OPTASSETPOOL SET INVENTORYDELIVERYGROUP_NEW = INVENTORYDELIVERYGROUP';
EXECUTE IMMEDIATE 'ALTER TABLE OPTASSETPOOL DROP COLUMN INVENTORYDELIVERYGROUP';
EXECUTE IMMEDIATE 'ALTER TABLE OPTASSETPOOL RENAME COLUMN INVENTORYDELIVERYGROUP_NEW TO INVENTORYDELIVERYGROUP';

EXECUTE IMMEDIATE 'ALTER TABLE OPTSOURCEDETAILS ADD INVENTORYDELIVERYGROUP_NEW VARCHAR2(1024)';
EXECUTE IMMEDIATE 'UPDATE OPTSOURCEDETAILS SET INVENTORYDELIVERYGROUP_NEW = INVENTORYDELIVERYGROUP';
EXECUTE IMMEDIATE 'ALTER TABLE OPTSOURCEDETAILS DROP COLUMN INVENTORYDELIVERYGROUP';
EXECUTE IMMEDIATE 'ALTER TABLE OPTSOURCEDETAILS RENAME COLUMN INVENTORYDELIVERYGROUP_NEW TO INVENTORYDELIVERYGROUP';

INSERT INTO lrsschemaproperties (modulename, propertyname) VALUES (v_module, v_property);
COMMIT;
END;
