DECLARE
 RESULTS NUMBER;
 V_MODULE VARCHAR2(100) := 'COLLATERAL';
 V_PROPERTY VARCHAR2(100) := 'COL-56607_ReuseAvailable_ReuseHolding';
BEGIN

 SELECT COUNT(1)
   INTO RESULTS
   FROM LRSSCHEMAPROPERTIES L
  WHERE L.MODULENAME = V_MODULE
    AND L.PROPERTYNAME = V_PROPERTY;

 IF RESULTS > 0 THEN
   RETURN;
 END IF;

 EXECUTE IMMEDIATE 'Alter table ColAgreementInstrument add maxReuseAvailable float(126) DEFAULT 0';
 EXECUTE IMMEDIATE 'Alter table ColAgreementInstrument add maxReuseHolding float(126) DEFAULT 0';

 INSERT INTO LRSSCHEMAPROPERTIES(MODULENAME, PROPERTYNAME) VALUES(V_MODULE,V_PROPERTY);

 COMMIT;

END;
/