DECLARE
 RESULTS NUMBER;
 V_MODULE VARCHAR2(100) := 'COLLATERAL';
 V_PROPERTY VARCHAR2(100) := 'COL_59381_LONGBOX_AGR_FEED';
BEGIN

 SELECT COUNT(1)
   INTO RESULTS
   FROM LRSSCHEMAPROPERTIES L
  WHERE L.MODULENAME = V_MODULE
    AND L.PROPERTYNAME = V_PROPERTY;

 IF RESULTS > 0 THEN
   RETURN;
 END IF;

 EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_AGREEMENT ADD (assetServiceLinkedAgrExtIds VARCHAR2(255), clientLinkedAgrExtIds VARCHAR2(255),autoUpdatePosition NUMBER(1))';

 INSERT INTO LRSSCHEMAPROPERTIES(MODULENAME, PROPERTYNAME) VALUES(V_MODULE,V_PROPERTY);

 COMMIT;

END;
/