DECLARE
 RESULTS NUMBER;
 V_MODULE VARCHAR2(100) := 'COLLATERAL';
 V_PROPERTY VARCHAR2(100) := 'COL_60491_Agreement_feed_Excel_feed_success_with_warning_message_related_to_SWIFTMessaging';
BEGIN

 SELECT COUNT(1)
   INTO RESULTS
   FROM LRSSCHEMAPROPERTIES L
  WHERE L.MODULENAME = V_MODULE
    AND L.PROPERTYNAME = V_PROPERTY;

 IF RESULTS > 0 THEN
   RETURN;
 END IF;

 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT add prinSWIFTMessaging varchar2(50)';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT add cptySWIFTMessaging varchar2(50)';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT add prinIMSWIFTMessaging varchar2(50)';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT add cptyIMSWIFTMessaging varchar2(50)';

 INSERT INTO LRSSCHEMAPROPERTIES(MODULENAME, PROPERTYNAME) VALUES(V_MODULE,V_PROPERTY);

 COMMIT;

END;
/