DECLARE
 RESULTS NUMBER;
 V_MODULE VARCHAR2(100) := 'COLLATERAL';
 V_PROPERTY VARCHAR2(100) := 'COL_60292_Issue_with_uploading_of_CCP_agreements_template_feed';
BEGIN

 SELECT COUNT(1)
   INTO RESULTS
   FROM LRSSCHEMAPROPERTIES L
  WHERE L.MODULENAME = V_MODULE
    AND L.PROPERTYNAME = V_PROPERTY;

 IF RESULTS > 0 THEN
   RETURN;
 END IF;

 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD bufferSection NUMBER(1)';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD principalBufferTypes CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD principalBufferLowerLimits CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD principalBufferUpperLimits CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD principalBufferTargets CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT add principalBufferCcy varchar2(50)';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD cptyBufferTypes CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD cptyBufferLowerLimits CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD cptyBufferUpperLimits CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD cptyBufferTargets CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT add cptyBufferCcy varchar2(50)';

 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imBufferSection NUMBER(1)';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imPrincipalBufferTypes CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imPrincipalBufferLowerLimits CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imPrincipalBufferUpperLimits CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imPrincipalBufferTargets CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT add imPrincipalBufferCcy varchar2(50)';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imCptyBufferTypes CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imCptyBufferLowerLimits CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imCptyBufferUpperLimits CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT ADD imCptyBufferTargets CLOB';
 EXECUTE IMMEDIATE 'Alter table FEED_STAGING_GOOD_AGREEMENT add imCptyBufferCcy varchar2(50)';

 INSERT INTO LRSSCHEMAPROPERTIES(MODULENAME, PROPERTYNAME) VALUES(V_MODULE,V_PROPERTY);

 COMMIT;

END;
/