DECLARE
results    NUMBER;
  v_module   VARCHAR2(100) := 'collateral';
  v_property VARCHAR2(100) := 'COL-56689_Add_additional_Security_UDF';
BEGIN

SELECT count(1)
INTO results
FROM lrsschemaproperties l
WHERE l.modulename = v_module
  AND l.propertyname = v_property;

IF results > 0
  THEN
    RETURN;
END IF;


EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf31 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf32 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf33 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf34 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf35 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf36 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf37 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf38 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf39 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf40 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf41 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf42 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf43 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf44 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf45 FLOAT(126)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf46 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf47 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf48 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf49 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf50 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf51 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf52 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf53 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf54 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf55 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf56 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf57 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf58 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf59 VARCHAR2(250)';
EXECUTE IMMEDIATE 'ALTER TABLE ColRptOutSecurity ADD udf60 VARCHAR2(250)';
INSERT INTO lrsschemaproperties (modulename, propertyname) VALUES (v_module, v_property);
COMMIT;
END;