DECLARE
results    NUMBER;
    v_module   VARCHAR2(100) := 'collateral';
    v_property VARCHAR2(100) := 'COL-57256_AHV_Enhancement_Im_Source';

BEGIN

SELECT count(1) INTO results FROM lrsschemaproperties l
WHERE l.modulename = v_module
  AND l.propertyname = v_property;

IF results > 0
    THEN
        RETURN;
END IF;

EXECUTE IMMEDIATE 'ALTER TABLE COLNETTEDSECURITYPARAMOUNT  ADD imSource  VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLNETTEDSECURITYPARAMOUNT  ADD imSourceAmount float(126) DEFAULT 0';
EXECUTE IMMEDIATE 'ALTER TABLE COLNETTEDSECURITYPARAMOUNT  ADD ownerAgreementAmount float(126) DEFAULT 0';
EXECUTE IMMEDIATE 'ALTER TABLE COLSECURITYPARAMOUNT  ADD imSource  VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLSECURITYPARAMOUNT  ADD imSourceAmount float(126) DEFAULT 0';
EXECUTE IMMEDIATE 'ALTER TABLE COLSECURITYPARAMOUNT  ADD ownerAgreementAmount float(126) DEFAULT 0';

EXECUTE IMMEDIATE 'ALTER TABLE COLRPTINASSETHOLDINGS  ADD imSource  VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLRPTINASSETHOLDINGS  ADD book VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLRPTINASSETHOLDINGS  ADD inventoryDeliveryGroup VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLRPTOUTASSETHOLDINGS  ADD imSource  VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLRPTOUTASSETHOLDINGS  ADD book VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLRPTOUTASSETHOLDINGS  ADD inventoryDeliveryGroup VARCHAR2(100)';

INSERT INTO lrsschemaproperties (modulename, propertyname) VALUES (v_module, v_property);
COMMIT;
END;