DECLARE
results    NUMBER;
    v_module   VARCHAR2(100) := 'collateral';
v_property VARCHAR2(100) := 'COL-57429_AHV_Enhancement_Im_Source_S2';

BEGIN

SELECT count(1) INTO results FROM lrsschemaproperties l
WHERE l.modulename = v_module
AND l.propertyname = v_property;

IF results > 0
THEN
RETURN;
END IF;

EXECUTE IMMEDIATE 'ALTER TABLE COLLETTERDETAILS  ADD ownerAgreement VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLLETTERDETAILS  ADD imSource  VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE COLLETTERDETAILS  ADD imSourceAmount float(126) DEFAULT 0';
EXECUTE IMMEDIATE 'ALTER TABLE COLLETTERDETAILS  ADD ownerAgreementAmount float(126) DEFAULT 0';

EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_ASSETBOOKING  ADD imSource  VARCHAR2(100)';
EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_ASSETBOOKING  ADD imSourceAmount float(126) DEFAULT 0';
EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_ASSETBOOKING  ADD ownerAgreementAmount float(126) DEFAULT 0';

INSERT INTO lrsschemaproperties (modulename, propertyname) VALUES (v_module, v_property);
COMMIT;
END;