-- 🔁 Rollback for PL/SQL V15.16.3.0.0.0__COL-61927.sql
ALTER TABLE COLRPTOUTAGREEMENTS DROP COLUMN prinTargetBuffer;
ALTER TABLE COLRPTOUTAGREEMENTS DROP COLUMN cptytargetbuffer;
ALTER TABLE COLRPTOUTAGREEMENTS DROP COLUMN imPrinTargetBuffer;
ALTER TABLE COLRPTOUTAGREEMENTS DROP COLUMN imcptyTargetBuffer;

DELETE FROM LRSSCHEMAPROPERTIES 
WHERE MODULENAME = 'collateralReports' 
  AND PROPERTYNAME = 'COL-61927_Colline_crashes_when_saving_agreement_report';