 DECLARE
 RESULTS NUMBER;
 V_MODULE VARCHAR2(100) := 'COLLATERAL';
 V_PROPERTY VARCHAR2(100) := 'COL50311_Corp_Action';
BEGIN

 SELECT COUNT(1)
   INTO RESULTS
   FROM LRSSCHEMAPROPERTIES L
  WHERE L.MODULENAME = V_MODULE
    AND L.PROPERTYNAME = V_PROPERTY;

 IF RESULTS > 0 THEN
   RETURN;
 END IF;

  EXECUTE IMMEDIATE 'ALTER TABLE COLAGREEMENTHEADER ADD CORPORATEACTIONPERIOD VARCHAR2(255) DEFAULT 0';
  EXECUTE IMMEDIATE 'ALTER TABLE COLAGREEMENTHEADER ADD SUBSTITUTIONDAYCOUNT NUMBER(19) DEFAULT -1';


 INSERT INTO LRSSCHEMAPROPERTIES(MODULENAME, PROPERTYNAME) VALUES(V_MODULE,V_PROPERTY);

 COMMIT;

END;
/