DECLARE
results    NUMBER;
  v_module   VARCHAR2(100) := 'collateral';
  v_property VARCHAR2(100) := 'COL-66132_issue_Feed_agreement';
BEGIN

SELECT count(1)
INTO results
FROM lrsschemaproperties l
WHERE l.modulename = v_module
  AND l.propertyname = v_property;

IF results > 0
  THEN
    RETURN;
END IF;

EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_AGREEMENT ADD SUBSTITUTIONDAYCOUNT2  VARCHAR2(50)';
EXECUTE IMMEDIATE 'UPDATE FEED_STAGING_GOOD_AGREEMENT SET SUBSTITUTIONDAYCOUNT2  = TO_CHAR(SUBSTITUTIONDAYCOUNT)';
EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_AGREEMENT DROP COLUMN SUBSTITUTIONDAYCOUNT';
EXECUTE IMMEDIATE 'ALTER TABLE FEED_STAGING_GOOD_AGREEMENT RENAME COLUMN SUBSTITUTIONDAYCOUNT2 TO SUBSTITUTIONDAYCOUNT';


INSERT INTO lrsschemaproperties (modulename, propertyname) VALUES (v_module, v_property);
COMMIT;
END;